apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3z8k
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0047-tenant/tkrw-pr712-0075-0047-app/devfile-sample-3z8k@sha256:d6aa82cbdb268b6fe937b55ed3af68fd05c5115d0ea1b66d62f366066dd30d7a
        name: my-nodejs
        resources: {}
status: {}
